version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: django
    versions:
    - "< 3, >= 2.a"
  - dependency-name: djangorestframework
    versions:
    - "< 3.9, >= 3.8.a"
  - dependency-name: pytest-django
    versions:
    - 4.1.0
